#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend shadowpost.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 313356-web-01 54.85.131.209:80
        server 313356-web-02 100.25.163.221:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart