#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
printf %s "
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend shadowpost.tech
    bind 0:80
    default_backend web_servers
    stats enable
    stats uri /haproxy-stats
    stats refresh 10s

backend web_servers
    balance roundrobin
    server 313356-web-01 54.85.131.209:85 check
    server 313356-web-02 100.25.163.221:85 check

listen stats
    bind :8080
    stats enable
    stats uri /haproxy-stats
    stats refresh 10s
" > /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart