#!/usr/bin/env bash
#Superstitious numbers
i=1
while ((i <= 20)); do
    echo "$i"
    case $i in
        4)
            echo "Bad luck from China"
            ;;
        9)
            echo "Bad luck from Japan"
            ;;
        17)
            echo "Bad luck from Italy"
            ;;
    esac
    ((i++))
done
