#!/usr/bin/env bash
#configures an Ubuntu server changing localhost and facebook
sudo cp /etc/hosts ~/hosts.new

sudo sed -i '/localhost/s/127.0.0.1/127.0.0.2/' ~/hosts.new
sudo sed -i '/facebook.com/s/157.240.11.35/8.8.8.8/' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
